"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Buffer__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Buffer__factory_1 = require("./Buffer__factory");
Object.defineProperty(exports, "Buffer__factory", { enumerable: true, get: function () { return Buffer__factory_1.Buffer__factory; } });
